//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Orders
    {
        public string FullName { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
